- name: set variable instance_1
  set_fact:
    name: "{{ instance_1.name }}"
    title_html : "{{ instance_1.title_html }}"
    name_directory : "{{ instance_1.name_directory }}"
    
- name: "Create directory {{ name_directory }}"
  file:
    path: /home/{{ ansible_user }}/{{ name_directory }}
    state: directory
    
- name: "Download data from git repo"
  git:
    repo: 'https://github.com/diranetafen/static-website-example.git'
    dest: /home/{{ ansible_user }}/webapp

- name: "Copy new template"
  template: 		
    src: index.html.j2
    dest: /home/{{ ansible_user }}/webapp/index.html

- name: "launch docker container"
  docker_container:
    name: "{{ instance_1.name }}"
    image: httpd
    ports: 
      - "{{ instance_1.port }}":"80"
    volumes:
      - /home/{{ ansible_user }}/webapp/:/usr/local/apache2/htdocs/:rw
 